title:          pages.feling.net
exclude:        ['README.md', 'CNAME']
include:        ['.well-known']
timezone:       Asia/shanghai
encoding:       'utf-8'
url:            https://pages.feling.net
permalink:      /:year/:month/:title.html
lsi:            true
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data", "html_toc"]