title:          feling
exclude:        ['README.md', 'CNAME']
timezone:       Asia/shanghai
encoding:       'utf-8'
url:            http://pages.feling.net
permalink:      /:year/:month/:title.html
lsi:            true
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data", "html_toc"]