title:          feling.net
exclude:        ['README.md', 'CNAME']
timezone:       Asia/shanghai
encoding:       'utf-8'
url:            http://pages.feling.net
ext_cn_site:    http://182.92.214.222
ext_us_site:    http://us.feling.net
permalink:      /:year/:month/:title.html
lsi:            true
markdown:       redcarpet
toc_levels:     3..4
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
